name: Get-AMD64-Docker-Images-Release(gzip)

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称:(多个镜像请用英文逗号分开)'
        required: true

jobs:
  pull_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker Images and Package
        run: |
          images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          uname -a
          cat /etc/*-release
          docker version
          docker system info
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/amd64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" -o "${image_name}_amd64.tar"
            gzip --version
            gzip --stdout --force --name --verbose --best "${image_name}_amd64.tar" > "${image_name}_amd64.tar.gz"
            rm "${image_name}_amd64.tar"
          done

      - name: List generated files (debug step)
        run: |
          echo "Preparing docker images list (.tar.gz) files:"
          find $GITHUB_WORKSPACE -name "*.tar.gz"
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: DockerTarBuilder-AMD64
          name: ${{ env.RELEASE_NAME }} gzip for AMD64
          body: |
            ### 使用镜像压缩包
            > 在导入镜像压缩包时:
            > 导入 **.tar.xz** 的镜像压缩包需要 **xz** 命令
            > 导入 **.tar.gz** 的镜像压缩包需要 **gzip** 命令
            ``` shell
            docker image load --input Docker_Images_Archive
            ```
            ### Docker导出镜像压缩包命令
            ``` shell
            # gzip
            docker image save repository:tag | gzip --stdout --force --name --verbose --best > repository_tag.tar.gz
            # xz
            docker image save repository:tag | xz --stdout --compress --format=xz -9 --extreme --threads=0 --verbose --verbose > repository_tag.tar.xz
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Docker images as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: DockerTarBuilder-AMD64
          files: ${{ github.workspace }}/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
