name: AMD64 Pull and Save Docker Image(xz)

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称:(多个镜像请用英文逗号分开)'
        required: true

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          uname -a
          cat /etc/*-release
          docker version
          docker system info
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/amd64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" -o "${image_name}_amd64.tar"
            xz --version
            xz --stdout --compress --format=xz -9 --extreme --threads=0 --verbose --verbose "${image_name}_amd64.tar" > "${image_name}_amd64.tar.xz"
            rm "${image_name}_amd64.tar"
          done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ${{ github.workspace }}/*.tar.xz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天